name: Butterfly
version: 1.1.8
main: me.butterfly.ButterflyMain
api-version: 1.21
author: Edminexus

commands:
  butterfly:
    description: Butterfly flight control

permissions:
  butterfly.admin:
    default: op